In [20]:
import pandas as pd

In [21]:
train_feature = pd.read_csv("task1_training_features.csv")
fix_feature = pd.read_csv("task1_negative_features_with_results.csv")

C:\Windows\Temp\ipykernel_7704\2851057744.py:2: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  fix_feature = pd.read_csv("task1_negative_features_with_results.csv")

In [23]:
train_feature.head(10)

,online_order,book_table,rate,dish_liked,approx_cost_for_one_people,menu_item,original_index,cuisines_word_embedding_PC1,cuisines_word_embedding_PC2,cuisines_word_embedding_PC3,...,Lavelle Road,MG Road,Malleshwaram,Marathahalli,New BEL Road,Old Airport Road,Rajajinagar,Residency Road,Sarjapur Road,Whitefield
0,1,1,4.1,7,400.0,0,0,1.372654,-1.112331,0.075874,...,0,0,0,0,0,0,0,0,0,0
1,1,0,4.1,7,400.0,0,1,3.158016,-0.282180,0.549734,...,0,0,0,0,0,0,0,0,0,0
2,1,0,3.8,7,400.0,0,2,0.368333,1.603899,-0.567267,...,0,0,0,0,0,0,0,0,0,0
3,0,0,3.7,1,150.0,0,3,-1.179024,-0.740344,-1.917100,...,0,0,0,0,0,0,0,0,0,0
4,0,0,3.8,2,300.0,0,4,-0.850827,-2.705486,0.586016,...,0,0,0,0,0,0,0,0,0,0
5,1,0,3.8,7,300.0,0,5,-1.179024,-0.740344,-1.917100,...,0,0,0,0,0,0,0,0,0,0
6,1,1,4.6,7,300.0,0,7,-0.906553,1.744607,0.068235,...,0,0,0,0,0,0,0,0,0,0
7,1,0,4.0,7,350.0,0,8,-0.104029,1.836365,-1.136420,...,0,0,0,0,0,0,0,0,0,0
8,1,0,4.2,7,275.0,0,9,-0.507681,0.810681,-0.196371,...,0,0,0,0,0,0,0,0,0,0
9,1,0,4.1,7,250.0,0,10,-1.628237,1.835902,-0.057209,...,0,0,0,0,0,0,0,0,0,0

In [24]:
fix_feature.head(10)

,online_order,book_table,rate,dish_liked,approx_cost_for_one_people,menu_item,original_index,cuisines_word_embedding_PC1,cuisines_word_embedding_PC2,cuisines_word_embedding_PC3,...,MG Road,Malleshwaram,Marathahalli,New BEL Road,Old Airport Road,Rajajinagar,Residency Road,Sarjapur Road,Whitefield,predicted_rate
0,0,0,3.6/5,1,400.0,0,6,2.183805,-0.788710,0.186807,...,0,0,0,0,0,0,0,0,0,3.289630
1,1,0,3.1/5,1,200.0,0,19,1.272900,1.144433,-0.854103,...,0,0,0,0,0,0,0,0,0,3.553556
2,0,0,3.6/5,1,450.0,0,22,-1.243700,1.813936,-0.618347,...,0,0,0,0,0,0,0,0,0,3.329236
3,0,0,3.2/5,1,300.0,0,25,-1.588587,1.750185,-0.286644,...,0,0,0,0,0,0,0,0,0,3.408800
4,0,0,3.3/5,1,250.0,0,27,-1.349903,2.014565,0.355777,...,0,0,0,0,0,0,0,0,0,3.485206
5,0,0,3.3/5,1,275.0,0,28,-1.243700,1.813936,-0.618347,...,0,0,0,0,0,0,0,0,0,3.394000
6,1,0,4.0/5,1,75.0,1,39,-1.037659,-0.791696,-1.929337,...,0,0,0,0,0,0,0,0,0,3.562413
7,0,0,3.9/5,1,150.0,0,41,-1.037659,-0.791696,-1.929337,...,0,0,0,0,0,0,0,0,0,3.751345
8,0,0,3.7/5,1,225.0,0,50,-1.037659,-0.791696,-1.929337,...,0,0,0,0,0,0,0,0,0,3.587111
9,1,0,4.1/5,1,75.0,1,51,-1.456105,2.215195,1.329901,...,0,0,0,0,0,0,0,0,0,3.561778

In [11]:
train_feature['predicted_rate'] = train_feature['rate']

In [12]:
# 检查列名和列数差异
train_columns = set(train_feature.columns)
fix_columns = set(fix_feature.columns)

# 找出不一致的列
missing_in_train = fix_columns - train_columns
missing_in_fix = train_columns - fix_columns

print("不一致的列:")
print("train_feature 缺少的列:", missing_in_train)
print("fix_feature 缺少的列:", missing_in_fix)

# 获取并输出两个文件的所有列名
# print("train_feature 列名:", train_feature.columns.tolist())

不一致的列:
train_feature 缺少的列: set()
fix_feature 缺少的列: set()

In [13]:
if list(train_feature.columns) == list(fix_feature.columns):
    # 合并 train_feature 和 fix_feature
    source = pd.concat([train_feature, fix_feature])
else:
    raise ValueError("train_feature 和 fix_feature 列数或列名不一致，无法合并")

In [14]:
source = source.sort_values(by="original_index").reset_index(drop=True)

In [15]:
# 对 'rate' 列进行处理，提取数值部分并转换为浮点数
source['rate'] = source['rate'].astype(str).str.extract(r'(\d+(\.\d+)?)')[0].astype(float)

# 对 'predicted_rate' 列进行相同处理
source['predicted_rate'] = source['predicted_rate'].astype(str).str.extract(r'(\d+(\.\d+)?)')[0].astype(float)

# 检查前几行，确认处理结果
print(source[['rate', 'predicted_rate']].head(10))

   rate  predicted_rate
0   4.1         4.10000
1   4.1         4.10000
2   3.8         3.80000
3   3.7         3.70000
4   3.8         3.80000
5   3.8         3.80000
6   3.6         3.28963
7   4.6         4.60000
8   4.0         4.00000
9   4.2         4.20000

In [16]:
# 统计 rate 列中非数值类型数据的数量，并输出前十个
non_numeric_rate_count = source[pd.to_numeric(source['rate'], errors='coerce').isna()].shape[0]
non_numeric_rate_samples = source[pd.to_numeric(source['rate'], errors='coerce').isna()].head(10)

# 统计 predicted_rate 列中非数值类型数据的数量，并输出前十个
non_numeric_predicted_rate_count = source[pd.to_numeric(source['predicted_rate'], errors='coerce').isna()].shape[0]
non_numeric_predicted_rate_samples = source[pd.to_numeric(source['predicted_rate'], errors='coerce').isna()].head(10)

# 打印结果
print("rate 列中非数值类型数据的数量:", non_numeric_rate_count)
print("rate 列中前 10 个非数值类型数据:")
print(non_numeric_rate_samples)

print("\npredicted_rate 列中非数值类型数据的数量:", non_numeric_predicted_rate_count)
print("predicted_rate 列中前 10 个非数值类型数据:")
print(non_numeric_predicted_rate_samples)

rate 列中非数值类型数据的数量: 9974
rate 列中前 10 个非数值类型数据:
     online_order  book_table  rate  dish_liked  approx_cost_for_one_people  \
72              0           0   NaN           1                        75.0
75              0           0   NaN           1                       250.0
84              0           0   NaN           1                        50.0
90              0           0   NaN           1                       250.0
91              0           0   NaN           1                       200.0
92              0           0   NaN           1                       100.0
107             0           0   NaN           1                       125.0
110             0           0   NaN           1                       100.0
113             0           0   NaN           1                        75.0
114             0           0   NaN           1                       150.0

     menu_item  original_index  cuisines_word_embedding_PC1  \
72           0              72                    -1.037659
75           0              75                    -1.037659
84           0              84                     4.591727
90           0              90                    -2.042324
91           0              91                    -1.037659
92           0              92                    -1.037659
107          0             107                    -1.456105
110          0             110                    -1.740093
113          0             113                    -1.838356
114          0             114                    -1.933474

     cuisines_word_embedding_PC2  cuisines_word_embedding_PC3  ...  MG Road  \
72                     -0.791696                    -1.929337  ...        0
75                     -0.791696                    -1.929337  ...        0
84                      0.336027                     0.309105  ...        0
90                      1.868841                     0.826004  ...        0
91                     -0.791696                    -1.929337  ...        0
92                     -0.791696                    -1.929337  ...        0
107                     2.215195                     1.329901  ...        0
110                     1.776707                     1.008882  ...        0
113                    -2.369572                    -0.348655  ...        0
114                     1.686435                     0.045060  ...        0

     Malleshwaram  Marathahalli  New BEL Road  Old Airport Road  Rajajinagar  \
72              0             0             0                 0            0
75              0             0             0                 0            0
84              0             0             0                 0            0
90              0             0             0                 0            0
91              0             0             0                 0            0
92              0             0             0                 0            0
107             0             0             0                 0            0
110             0             0             0                 0            0
113             0             0             0                 0            0
114             0             0             0                 0            0

     Residency Road  Sarjapur Road  Whitefield  predicted_rate
72                0              0           0        3.575689
75                0              0           0        3.453778
84                0              0           0        3.672735
90                0              0           0        3.493481
91                0              0           0        3.566952
92                0              0           0        3.743587
107               0              0           0        3.564889
110               0              0           0        3.664889
113               0              0           0        3.615963
114               0              0           0        3.582741

[10 rows x 75 columns]

predicted_rate 列中非数值类型数据的数量: 0
predicted_rate 列中前 10 个非数值类型数据:
Empty DataFrame
Columns: [online_order, book_table, rate, dish_liked, approx_cost_for_one_people, menu_item, original_index, cuisines_word_embedding_PC1, cuisines_word_embedding_PC2, cuisines_word_embedding_PC3, cuisines_word_embedding_PC4, cuisines_word_embedding_PC5, cuisines_word_embedding_PC6, cuisines_word_embedding_PC7, cuisines_word_embedding_PC8, cuisines_word_embedding_PC9, cuisines_word_embedding_PC10, Buffet, Cafes, Delivery, Desserts, Dine-out, Drinks & nightlife, Pubs and bars, multiple_types, Bakery, Bar, Beverage Shop, Cafe, Casual Dining, Delivery.1, Dessert Parlor, Dhaba, Fine Dining, Food Court, Food Truck, Kiosk, Lounge, Mess, Microbrewery, Pub, Quick Bites, Sweet Shop, Takeaway, BTM, Banashankari, Bannerghatta Road, Basavanagudi, Bellandur, Brigade Road, Brookefield, Church Street, Electronic City, Frazer Town, HSR, Indiranagar, JP Nagar, Jayanagar, Kalyan Nagar, Kammanahalli, Koramangala 4th Block, Koramangala 5th Block, Koramangala 6th Block, Koramangala 7th Block, Lavelle Road, MG Road, Malleshwaram, Marathahalli, New BEL Road, Old Airport Road, Rajajinagar, Residency Road, Sarjapur Road, Whitefield, predicted_rate]
Index: []

[0 rows x 75 columns]

In [17]:
# 将 rate 列中的所有空值或非数值类型数据替换为 0
source['rate'] = pd.to_numeric(source['rate'], errors='coerce').fillna(0)

In [18]:
source['new_rate'] = (0.6 * source['rate'] + 0.4 * source['predicted_rate']).round(1)
source.to_csv("source.csv", index=False) 
print("第二步完成：已合并 train_feature 和 fix_feature，添加 new_rate 列，并生成 source.csv 文件")

第二步完成：已合并 train_feature 和 fix_feature，添加 new_rate 列，并生成 source.csv 文件